rise-tools/rise-tools

.github/workflows/unit-tests.yml, jest/setup.js, package.json, packages/core/src/__tests__/refs.test.tsx, packages/core/src/__tests__/template.test.tsx, packages/ui-tamagui/src/__tests__/index.test.tsx
This PR configures `jest` to always run from source and configures Github Action to test it and report. I am unifying testing environment to be web. Before, as you can see from the snapshots, Tamagui was rendering React Native views (and generating warnings about <Text /> not existing in the current environment), despite testing environment being `jsdom`. This is now fixed and unified.
=> feat: add CI for tests and configure Jest

.gitignore, .vscode/settings.json, .vscode/tasks.json
Open command palette in VSCode and choose: "Preferences: Open keybindings shortcuts (JSON)" and paste the following:
```json
[{
"key": "cmd+shift+r",
"command": "workbench.action.tasks.runTask",
"args": "Start all servers"
}]
```
Then, press "CMD + SHIFT + R" and see this run automatically.
Otherwise, w/o shortcut:
CMD SHIFT P to open command palette, "Tasks: Run Task" and choose "Start all servers"
Here's what it looks like:
=> feat: add visual studio script to automatically run all servers

packages/playground/src/connection-form.tsx
We use branded types to render different inputs depending on what as `schema`. For default values, however, we only accept plain values. We need to exclude `z.BRAND` from the type to avoid type error when passing default values in other parts of the codebase. 
This utility type overwrites any union that includes "string" to just string. It's not future proof, but works for this particular use case.
=> fix: default type w/o zod branded

apps/mobile/metro.config.js, example/server/server.ts, example/server/state-schema.ts, example/server/ui.ts, packages/kit/src/Form.tsx, packages/kit/src/SortableList.tsx, packages/kit/src/index.tsx, packages/kit/tsconfig.json, packages/react/src/template.tsx
This PR adds support for rendering custom form components by the server. Once completed, I plan to remove `ts-form` and `connection-form` entirely and switch to rendering `<Template />` component with form definition.
Notable change is making event handlers `async` on the client. That way, we can `await` on e.g. `onPress` that results in an update being sent to the server. If server responds with something, that can be handled (e.g. perform local update, display an error). That functionality will be added in the future iteration.
=> feat: form support 

example/server/ui.ts, packages/tamagui/src/index.tsx
This PR is a perfect example of why Tamagui is awesome. The `asChild` makes it so easy to combine different components, e.g. AlertClose with a custom Form button. Simply awesome.
PS. Ignore the `warning`, will be fixed in another PR.
=> feat: move form into a modal

example/server/ui.ts, packages/kit/src/Form.tsx, packages/playground/src/screens/connect.tsx, packages/react/src/__tests__/refs.test.tsx, packages/react/src/__tests__/template.test.tsx, packages/react/src/events.native.ts, packages/react/src/events.ts, packages/react/src/refs.tsx, packages/react/src/template.tsx, packages/tamagui/src/__tests__/index.test.tsx, packages/ws-server/src/ws-rnt-server.ts
In this PR, I remove the logic responsible for computing and assigning keys on the client. It turned out to be redundant because of the following reasons:
- keys are not required when there's single child
- when there's an array, keys should be assigned explicitly by the user or alternatively, computed inside JSX factory (like React does), instead of assigning "key={index}" as before, as that does not provide much value
Despite that change, no change required on the server. This is because server was made back when keys were required to avoid warnings. So we're moving back to the roots.
This PR turns `path` into what it used to be before - a store path. The path will change for a referenced component and all its children to point to the path that they come from. This will be necessary to …
=> feat: clean-up paths

packages/playground/src/screens/home.tsx
As per discussion in the last PR, we don't want to render example connections when custom were provided by the user.
=> feat: do not render default connections when custom are set

example/demo/src/inventory/ui.ts, packages/playground/src/screens/connection.tsx, packages/react/src/__tests__/events.test.ts, packages/react/src/__tests__/refs.test.tsx, packages/react/src/__tests__/template.test.tsx, packages/react/src/events.ts, packages/react/src/index.tsx, packages/react/src/refs.tsx, packages/react/src/response.ts, packages/react/src/template.tsx, packages/ws-client/src/__tests__/data-source.test.ts, packages/ws-client/src/data-source.ts, packages/ws-server/src/data-source.ts
This PR adds ability for the data source to have impact on client-side behavior after responding to the request. It misses some tests and fine tuning, but I wanted to make sure we have directional agreement before committing more time to it. After initial approval, I will go ahead and complete missing tests.
On a high-level, from your event handler, you can return either plain object or an instance of Response:
```ts
{
$: 'component',
component: 'RiseForm',
props: {
onSubmit: handler((values) => {
// handle on press, then
return res.json()
// send action
.action(['navigate', 'goBack'])
// or more
.action(['some-other-action'])
})
}
}
```
Above example will instruct client to perform "goBack" navigation which is specific to Rise mobile application after 
succesfully handling action on the …
=> feat: ability to respond to events with client-side actions

packages/react/src/__tests__/utils.test.ts, packages/react/src/template.tsx, packages/react/src/utils.ts
Alternative to Array.prototype.every that throws if items are not all of the same type. That way, we can safely check for an array of "actions". Otherwise, current code would lead to [action(), "whatever"] to pass type checking, but lead to unexpected behavior during runtime.
After this PR, it will throw.
=> feat: add utility assertion for uniform arrays

apps/mobile/package.json, apps/mobile/src/screens/connection.tsx, apps/mobile/tsconfig.json, docs/docs/kit/haptics.md, example/demo/package.json, example/demo/src/ui-controls/ui.tsx, example/demo/tsconfig.json, package-lock.json, packages/kit-expo-router/package.json, packages/kit-expo-router/src/index.ts, packages/kit-expo-router/src/server.ts, packages/kit-haptics/README.md, packages/kit-haptics/package.json, packages/kit-haptics/src/index.ts, packages/kit-haptics/src/server.ts, packages/kit-haptics/tsconfig.json, packages/kit-tamagui-toast/package.json, packages/kit-tamagui-toast/src/index.ts, packages/kit-tamagui-toast/src/server.ts, packages/react/src/refs.tsx, packages/react/src/rise.tsx, packages/react/src/utils.ts, tsconfig.build.json, tsconfig.json
Fixes #92 
Validation:
- fix an error when validating action would always throw an error
- add better error message for invalid payloads
- add validators for all actions (in expo router, toast and haptics). In the future, this will be less boilerplate when we use `Typia` (can infer validator from TS type)
- Ensure validator (such as Zod) returns expected shape from `validate` function
- Slightly more convenient `ActionsDefinition` helper
=> feat: add kit-haptics, add validation to other kit action packages, better validation errors

apps/mobile/package.json, apps/mobile/src/screens/connection.tsx, apps/mobile/tsconfig.json, docs/docs/kit/svg.md, example/demo/package.json, example/demo/src/ui-controls/ui.tsx, example/demo/tsconfig.json, package-lock.json, packages/kit-svg/README.md, packages/kit-svg/package.json, packages/kit-svg/src/index.ts, packages/kit-svg/src/server.ts, packages/kit-svg/tsconfig.json, tsconfig.build.json, tsconfig.json
Fixes #97 
Adds `react-native-svg` supported by latest Expo SDK.
The example is quite ugly, but I just copied some examples from React Native SVG to demonstrate various functionality
- static SVG
- SVG from URI
- SVG as string
This is great opportunity to get creative and include some fun stuff, so let's get creative!
=> feat: add @rise-tools/kit-svg

apps/mobile/package.json, apps/mobile/src/screens/connection.tsx, apps/mobile/tsconfig.json, docs/docs/kit/icons.md, docs/docs/kit/index.md, example/demo/package.json, example/demo/src/delivery/ui.tsx, example/demo/src/ui-controls/ui.tsx, example/demo/tsconfig.json, package-lock.json, packages/kit-lucide-icons/README.md, packages/kit-lucide-icons/package.json, packages/kit-lucide-icons/src/index.tsx, packages/kit-lucide-icons/src/server.ts, packages/kit-lucide-icons/tsconfig.json, packages/kit/src/index.tsx, packages/kit/src/server/bindings.ts, tsconfig.build.json, tsconfig.json
Moving components from "kit" to prepare it for being umbrella.
=> feat: add "@rise-tools/kit-lucide-icons"

packages/server/src/__tests__/model-view.test.ts, packages/server/src/model-view.ts
View model was not firing subscription updates when the dependency changes. This was never implemented.
Using a timeout(1) to handle cases when two view dependencies change, we only want to trigger one update
=> fix: view model update when subscribed

package-lock.json, packages/create-rise/package.json, packages/create-rise/src/cli.ts, packages/create-rise/src/theme.ts, packages/create-rise/src/utils.ts
Another PR to visually please our beloved users!
* Added icons, used `chalk` to make `create-rise` "pop"
* Added option to skip installing packages (`astro` does this, thought it would be nice if we don't support multiple package managers for now)
* Replaced `inquirer` with `@inquirer/prompts` its successor (with a bit cleaner api and access to `theme`  type) 
* Themed inquirer prompts with `stylePrompt` fnc
Feel free to add your opinion's in this PR.
=> feat: improve `create-rise` styling

packages/create-rise/package.json, packages/create-rise/src/cli.ts
Small PR that introduces `--yes` flag to `create-rise`, to comply with requirements of fully automated scenario.
* also additional encouragement to download `rise-playground`!
=> feat: add prompt skip flag

docs/docs/kit/react-navigation.md, example/demo/src/index.ts, packages/kit-react-navigation/src/server.ts
This PR builds on top of work by @arpitBhalla with a few modifications to prepare the code for upcoming screen options (pending PR #158).
Instead of specifying type of `path` via `keyof typeof path`, it adds support for future type checking of screen params.
The following are type-checked:
```ts
navigate('form')
navigate('home', { params: { userId: 5 }})
```
for the following
```
interface Navigate {
screens: {
form: void
home: { userId: 5 }
}
}
```
In the future, we will automatically infer the type of params, as long as you passed in lookup type model (that takes params). 
If params are defined, options (second argument to navigate) are required, otherwise optional. Aside from `options.params`, you can also specify `screen` settings (will be implemented in a follow-up via #158).
=> feat: type safety for `navigate` action in React Navigation 

.gitignore, packages/server/src/__tests__/types.test-d.ts, packages/server/src/types.ts, test/config.mjs
- Added tests for types (OMG, I love `vitest` so much!)
- Added support for nested/nested lookup models (wasn't working for some reason)
- Removed support for "objects" of models (this is currently not supported, we can always add it back)
CC: @arpitBhalla
=> feat: infer lookup path for nested models and add unit tests

docs/docs/contributors.md
Hey,
Noticed the demo server or the playground requires the builds for the packages. Adding the build command info to the Contributor doc's page. Starting small with this change and looking forward to working on bigger PRs later 😄. let me know if I need to change anything like the position or styling of the info.
=> readme: added build step before running the playground/demo server.

.gitignore, package-lock.json, packages/cli/package.json, packages/cli/src/utils.ts, packages/server/src/utils.ts
Given time constraints, this is much simpler and smaller implementation of original Tunnel idea we had in mind.
Key highlights:
- DigitalOcean VPS running [Sish](https://github.com/antoniomika/sish) via Docker Compose (I took me a while to figure this out). We're on $6 plan a month. We will see how long it lasts.
- We use [SSH tunneling](https://www.ssh.com/academy/ssh/tunneling)
- We use `*.proxy.rise.tools` subdomain
Benefits:
- No additional tools required. Just SSH client.
- No cloud service involved. Less things to maintain. We will eventually need it (more on it later).
How this works:
- Project is assigned its unique ID (via `uuid.v4()`) 
- Project ID is stored in `.rise/projectId` file
- Tunnel will be open on each server start automatically, with 5s timeout 
- Hostname is fixed …
=> feat: automatically expose connection via Rise Proxy

example/demo/package.json, example/demo/src/index.ts, example/demo/tsconfig.json, package-lock.json, packages/cli/package.json, packages/cli/src/index.ts, packages/cli/src/theme.ts, packages/cli/src/utils.ts, packages/cli/src/welcome.ts, packages/cli/src/zx.ts, packages/cli/tsconfig.json, packages/server/package.json, packages/server/src/http-server.ts, packages/server/src/server.ts, packages/server/src/types.ts, packages/server/src/utils.ts, packages/server/src/ws-server.ts, packages/server/tsconfig.json, templates/blank-playground/package.json, templates/blank-playground/src/server.ts
Here's the behavior:
While connecting:
Failed (maximum timeout: 5s)
Connected:
QR Code is displayed as always.
=> feat: fallback UI for the tunnel in the CLI 

apps/mobile/src/back-button.tsx, apps/mobile/src/connection.tsx, apps/mobile/src/screens/connection.tsx, apps/mobile/src/screens/home.tsx, apps/mobile/src/screens/index.tsx
- Do not hardcode examples, instead, use default screen for our example and render it in a partial view
- To do so, we need to slightly overwrite "navigate" action in that partial screen to properly navigate into Rise navigator
- Remove "Share" option for default example. We always render it. Also, it would not work, because there's special handling for "example" ID anyways
- That said, dropdown now has just one option for builtin connection - "Go back". Decided to make the Rise logo always go back for builtin connection (no dropdown). Saves one extra click.
- When you have custom connection, the "Example" will render as always, at the end.
Questions:
- How should the "Example" be named? Right now, it's just "Example".
Screenshots:
=> feat: replace hardcoded list of examples with partial Rise screen

example/demo/src/index.ts, packages/cli/src/utils.ts, packages/cli/src/welcome.ts
While our demo server is not really production ready (yet), nor its this pipeline intended to be production ready, we did deploy our demo server to Render with tunnel option, so that everyone can continue accessing our demo from the conference by the QR code.
Unfortunately, that means [I had to create a separate Github repository, commit `.rise` folder to it and deploy the entire project.](https://github.com/rise-tools/vibes-example-server/tree/main/.rise) Otherwise, `setupRiseTools` wouldn't know what projectKey to use.
This PR adds ability to pass it via argument, which can e.g. be an environmental variable. That way, we can setup deployments without leaking secrets.
Once merged and released, I will open source (make public) repository with "vibes" example that is currently private due …
=> feat: easier deployment of dev server to production

packages/server/src/__tests__/model-query.test.ts, packages/server/src/model-query.ts
I noticed the query model was not loading as expected when a client subscribes to it (or through a view)
This fixes the issue and includes a test to verify the behavior and prevent regressions
=> fix: query model should auto-load on subscribe

packages/react/src/__tests__/jsx-runtime.test.tsx, packages/react/src/jsx-runtime.tsx
You can now return more than just component definitions from within your server side helpers.
=> feat: allow all types of ReactNode JSX to be rendered on the server

packages/react/src/streams.ts
This lack of memoization was causing aggressive re-subscription internally to rise
=> fix: streams: avoid extra re-subscription

packages/kit/src/client/DraggableFlatList.tsx
- Use TouchableWithoutFeedback to mitigate the issue where the pressed state is stuck
- onPress callback for each item
- onPress callback for the whole component
Note: The issue is still present where the pressed state gets stuck down after dragging an item. This is a bug because the user needs to press it twice for the onPress callback to fire. But at least the user is not left with a bad visual state. Obviously we want a real fix for this, and when we have one, we can switch back to TouchableOpacity
=> feat: improves DraggableFlatList

packages/react/src/__tests__/rise.test.tsx, packages/react/src/rise.tsx
Following up to previous PR, this adds ability to render Iterables, not just Arrays, as children and props. While our transportation mechanism currently does not support transporting anything but arrays, this makes it aligned with what server outputs, in case it gets passed directly as a prop.
Previously, this would throw an error that objects can't be rendered, which is correct, just not for iterables!
=> feat: allow rendering iterable elements on the client

packages/react/package.json, packages/react/src/jsx-dev-runtime.ts, tsconfig.json
When setting `jsxImportSource` to `@rise-tools/react`, certain bundlers may choose to use dev runtime (while in development). 
We must export `jsx-dev-runtime` with `jsxDev` and `jsxsDev`. We don't have any dev-specific behavior at this point, hence simple re-export.
=> feat(jsx): add `jsx-dev-runtime`

packages/react/src/events.native.ts
Historically, we had this empty file so React Native can build (events had some references to node:crypto).
Now, it's not needed. We're actually rendering some Rise JSX inside React Native application (for fallback UI) and this is breaking it.
=> fix: rendering Rise JSX from React Native / Metro context

packages/react/src/__tests__/jsx-runtime.test.tsx, packages/react/src/jsx-runtime.tsx, templates/full/src/inventory/ui.tsx, templates/full/src/vibes/ui.tsx
Aside from fixing the warning itself, I tried to simplify and make the naming inside JSX less confusing. This file is evolving (as JSX support is still experimental) and I felt like certain things did not make much sense anymore!
Mainly:
- Fixed wrong comment (a bit misleading) as far as what is the return type of `componentFactory`
- Removed `RiseElement` and `ReactNode` types in favour of `ServerModelState`. That allowed to remove type casting and other workarounds that were present in this PR in earlier commits
=> fix: warning about missing keys when using server-side helpers

packages/react/src/jsx-dev-runtime.ts, packages/react/src/jsx-runtime.tsx
JSX 
```
const View = (
<>
<div />
</>
)
```
is transformed to this
```
import { jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
const View = /*#__PURE__*/_jsx(_Fragment, {
children: /*#__PURE__*/_jsx("div", {})
});
```
As you can see, `Fragment` from `jsx-runtime` is used as `componentFactory`, just like any other component. Beforehand, we didn't have it, so it was undefined. 
We actually already export it from `jsx-runtime`, so I just added it to `jsx-dev-runtime` too to make it work and that `if` is no longer needed.
=> refactor: remove dead Fragment code

packages/react/src/jsx-dev-runtime.ts, packages/react/src/jsx-runtime.tsx
jsxDEV has different signature, there's no `jsxsDEV`, it takes `isStatic` as an additional boolean argument. We can't just export two factories, one for dynamic, second for static, we have to handle it differently, hence the change.
FWIW the handling is very similar to how React does this internally now! 
https://github.com/facebook/react/blob/main/packages/react/src/jsx/ReactJSXElement.js#L490-L501
(note explicit boolean)
```tsx
const profile = (
<div>
<h3>{[user.firstName, user.lastName].join(" ")}</h3>
</div>
);
```
```tsx
import { jsxDEV as _jsxDEV } from "react/jsx-dev-runtime";
const _jsxFileName = "input.jsx";
const profile = _jsxDEV("div", {
children: [
_jsxDEV("img", {
src: "avatar.png",
className: "profile",
}, undefined, false, { fileName: _jsxFileName, lineNumber: 3, …
```
=> fix: proper handling of static children in dev runtime
